global:
  scrape_interval: 30s
  scrape_timeout: 20s
  evaluation_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 20s
      api_version: v1

scrape_configs:
  - job_name: adlsdlp4b
    honor_timestamps: true
    scrape_interval: 30s
    scrape_timeout: 20s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["adlsdlp4b:80"]