global:
  scrape_interval: 30s
  scrape_timeout: 20s
  evaluation_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 20s
      api_version: v1

scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 30s
    scrape_timeout: 20s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["prometheus_adlsdlp4b:9090"]

  - job_name: adlsdlp4b
    static_configs:
      - targets: ["160.85.119.33:9100"]