{
 "title": "Server-room temperatur",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "GS Server-room",
   "type": "text",
   "description": "This dashboard was built to monitor the temperature and humidity in the server room next to the robotics lab. It displays the current values, the changes in temperature over the past 7 days, and the mean values of temperature and humidity since the first measurement up to the present.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "# Server-room\n\nThis dashboard was built to monitor the temperature and \nhumidity in the server room next to the robotics lab. \nIt displays the current values, the changes in temperature, \nand the mean values of temperature and humidity."
   }
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"server_room\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"environmental_data\")\r\n  |> filter(fn: (r) => r._field == \"temperature\")\r\n  |> last()\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"server_room\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"environmental_data\")\r\n  |> filter(fn: (r) => r._field == \"humidity\")\r\n  |> last()\r\n\r\n"
    }
   ]
  },
  {
   "title": "Averages",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"server_room\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"environmental_data\")\r\n  |> group(columns: [\"_field\"])\r\n  |> mean()\r\n"
    }
   ]
  },
  {
   "title": "Temperature development",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"server_room\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"environmental_data\")\r\n  |> filter(fn: (r) => r._field == \"temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n\r\n"
    }
   ]
  }
 ]
}